### PR TITLE
Update to 4.5.2 and 4.1.9

### PR DESCRIPTION
**Pull request by gerardorochin**
https://www.elastic.co/blog/kibana-4-5-2-and-4-1-9

### CODE REVIEW

**Comment by yosifkit** [comment]
LGTM

**Comment by tianon** [comment]
Any idea why they didn't tag these in their Git repo? (which is why our current `update.sh` isn't picking them up)

**Comment by tianon** [comment]
4.5.2 would get picked up if we fix the `TODO` I left in `update.sh`, but that still doesn't help 4.1.9 :disappointed:

**Comment by tianon** [comment]
Pushed 4ec7dcc for 4.5.2 `update.sh` fix, but I think we should probably merge this and figure out `update.sh` issues as a separate concern. :disappointed:

**Pull request merged**
