### PR TITLE
Add Alpine variant to Kibana.

### PR DESCRIPTION
**Pull request by sylus**
I was hoping to get Alpine support for Kibana in.

I think this P.R. still needs work but was hoping for advice that am on the right track? Any and all feedback is welcome as still learning :)

I adjusted the ./update.sh code so it doesn't scan directories instead expects an input. This is because some of the older versions are just to0 different and won't work with a global template.

I regenerated the 5.0 folder with:

./update.sh 5.0

### CODE REVIEW

**Comment by sylus** [comment]
I'd like to do logstash + elasticsearch as well but will wait for feedback :)

**Comment by yosifkit** [comment]
The only problem I notice is an `apk add --update` on one line instead of `--no-cache`.  I am sad about the lack parity between the regular and alpine variants :cry:

``` diff
diff --git a/5.0/Dockerfile b/5.0/alpine/Dockerfile
index e4821e7..44e057e 100644
--- a/5.0/Dockerfile
+++ b/5.0/alpine/Dockerfile
@@ -1,53 +1,30 @@
-FROM debian:jessie
-
-# add our user and group first to make sure their IDs get assigned consistently
-RUN groupadd -r kibana && useradd -r -m -g kibana kibana
-
-RUN apt-get update && apt-get install -y \
-       ca-certificates \
-       wget \
-   --no-install-recommends && rm -rf /var/lib/apt/lists/*
-
-# grab gosu for easy step-down from root
-ENV GOSU_VERSION 1.7
-RUN set -x \
-   && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)" \
-   && wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc" \
-   && export GNUPGHOME="$(mktemp -d)" \
-   && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
-   && gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
-   && rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc \
-   && chmod +x /usr/local/bin/gosu \
-   && gosu nobody true
-
-# grab tini for signal processing and zombie killing
-ENV TINI_VERSION v0.9.0
-RUN set -x \
-   && wget -O /usr/local/bin/tini "https://github.com/krallin/tini/releases/download/$TINI_VERSION/tini" \
-   && wget -O /usr/local/bin/tini.asc "https://github.com/krallin/tini/releases/download/$TINI_VERSION/tini.asc" \
-   && export GNUPGHOME="$(mktemp -d)" \
-   && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 6380DC428747F6C393FEACA59A84159D7001A4E5 \
-   && gpg --batch --verify /usr/local/bin/tini.asc /usr/local/bin/tini \
-   && rm -r "$GNUPGHOME" /usr/local/bin/tini.asc \
-   && chmod +x /usr/local/bin/tini \
-   && tini -h
-
-# https://www.elastic.co/guide/en/kibana/4.4/setup.html#kibana-apt
-# https://packages.elasticsearch.org/GPG-KEY-elasticsearch
-RUN apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 46095ACC8548582C1A2699A9D27D666CD88E42B4
+FROM alpine:3.3

 ENV KIBANA_MAJOR 5.0
 ENV KIBANA_VERSION 5.0.0-alpha1

-#RUN echo "deb http://packages.elastic.co/kibana/${KIBANA_MAJOR}/debian stable main" > /etc/apt/sources.list.d/kibana.list
-RUN echo 'deb http://packages.elastic.co/kibana/5.0.0-alpha/debian stable main' > /etc/apt/sources.list.d/kibana.list
-# TODO figure out what's going on here and what it'll settle to for 5.0 GA
-
-RUN set -x \
-   && apt-get update \
-   && apt-get install -y --no-install-recommends kibana=$KIBANA_VERSION \
-   && chown -R kibana:kibana /opt/kibana \
-   && rm -rf /var/lib/apt/lists/*
+# persistent / runtime deps
+RUN apk add --no-cache --virtual .persistent-deps \
+   ca-certificates \
+   curl
+
+# tiny
+RUN apk add --update --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ tini
+
+RUN set -xe \
+   && apk add --no-cache --virtual .kibana-deps \
+   bash \
+   nodejs \
+   su-exec \
+   && curl -LO https://download.elasticsearch.org/kibana/kibana/kibana-${KIBANA_VERSION}-linux-x64.tar.gz \
+   && mkdir -p /opt/ \
+   && tar xzf /kibana-${KIBANA_VERSION}-linux-x64.tar.gz -C /opt/ \
+   && mv /opt/kibana-${KIBANA_VERSION}-linux-x64 /opt/kibana \
+   && rm /opt/kibana/node/bin/node \
+   && rm /opt/kibana/node/bin/npm \
+   && ln -s /usr/bin/node /opt/kibana/node/bin/node \
+   && ln -s /usr/bin/npm /opt/kibana/node/bin/npm \
+   && rm -rf /kibana-${KIBANA_VERSION}-linux-x64.tar.gz

 ENV PATH /opt/kibana/bin:$PATH

```

**Comment by sylus** [comment]
Thank you very much for the feedback!

I fixed the `--no-cache` for tini. 

Unfortunately the parity is off between the two. I started to notice that other official alpine variants are using su-exec instead of gosu so made the switch, and unfortunately the only compatible version of tini for musl is through the alpine edge.

**Comment by shouze** [comment]
Looks great, what is the size of the alpine variant image variant compared to the regular one?
It's a bit sad about gosu but should be ok.

@sylus the travis build failed on alpine variant because of some curl download error/timeout, could you push again to make the build green?

ping @yosifkit are you ok to merge after that?

**Comment by haizaar** [comment]
@sylus,
- Do you plan backports for Kibana 4.5?
- Why are you replacing kibana's node/npm with apline's one?

**Comment by mi-hol** [comment]
@tianon re the 'travis build failed on alpine variant because of some curl download error/timeout' mentioned, could this be caused by a similar root cause as with logstash alpine build?

Completing this would finish ELK-alpine :)

**Comment by yosifkit** [comment]
Closing feature requests, since this image is being deprecated.

>This image is officially deprecated in favor of [the `kibana` image provided by elastic.co](https://www.elastic.co/guide/en/kibana/current/_pulling_the_image.html) which is available to pull via `docker.elastic.co/kibana/kibana:[version]` like `5.2.1`. This image will receive no further updates after 2017-06-20 (June 20, 2017). Please adjust your usage accordingly.
>
>Elastic provides open-source support for Kibana via the [elastic/kibana GitHub repository](https://github.com/elastic/kibana) and the Docker image via the [elastic/kibana-docker GitHub repository](https://github.com/elastic/kibana-docker), as well as community support via its [forums](https://discuss.elastic.co/c/kibana).

**Pull request closed without merging**
