### PR TITLE
[WIP] Update to 5.0.0-beta1

### PR DESCRIPTION
**Pull request by gerardorochin**
https://www.elastic.co/blog/kibana-5-0-0-beta1

### CODE REVIEW

**Comment by gerardorochin** [comment]
Build local and is returned this error:

```
Reading state information...
The following NEW packages will be installed:
  kibana
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 40.5 MB of archives.
After this operation, 147 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  kibana
```

You have any idea for cause this? @tianon

**Comment by yosifkit** [comment]
I tested the `apt-get update` in Debian sid with the kibana sources and this is what I get:

```
W: The repository 'https://artifacts.elastic.co/packages/5.x-prerelease/apt stable Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

So I looks like their new `artifacts.elastic.co` deb repo is not properly signed.

**Comment by gerardorochin** [comment]
Ok, still waiting for repository to be signed

**Comment by markwalkom** [comment]
Obvious question is obvious, but you imported the key, as per [here](https://www.elastic.co/guide/en/kibana/current/setup-repositories.html#kibana-apt)?

I just tried the process in the docs and had no issues with signing.

**Comment by tianon** [comment]
@markwalkom yes, see https://github.com/docker-library/kibana/pull/55/files#diff-47939014d83e4cb69131758af1d88f37L37 (https://github.com/elastic/kibana/issues/8459#issuecomment-249377433 is also relevant)

In any case, I've restarted the Travis build just in case something has changed between @gerardorochin's latest test and now. :+1:

**Comment by tianon** [comment]
Just for good measure, I've also just re-downloaded the URL noted in the documentation to verify it against the `46095ACC8548582C1A2699A9D27D666CD88E42B4` we pull from the keyserver pool:

``` console
root@fe42b2af9a06:/# wget -qO- https://packages.elastic.co/GPG-KEY-elasticsearch | gpg --import
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key D88E42B4: public key "Elasticsearch (Elasticsearch Signing Key) <dev_ops@elasticsearch.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
root@fe42b2af9a06:/# gpg --fingerprint
/root/.gnupg/pubring.gpg
------------------------
pub   2048R/D88E42B4 2013-09-16
      Key fingerprint = 4609 5ACC 8548 582C 1A26  99A9 D27D 666C D88E 42B4
uid                  Elasticsearch (Elasticsearch Signing Key) <dev_ops@elasticsearch.org>
sub   2048R/60D31954 2013-09-16

```

**Comment by tianon** [comment]
Definitely still getting `WARNING: The following packages cannot be authenticated!` (https://travis-ci.org/docker-library/kibana/jobs/162007806#L667).

**Comment by gerardorochin** [comment]
The problem is in new repo https://artifacts.elastic.co/packages/5.x-prerelease/apt
the repo https://packages.elastic.co/kibana/4.6/debian is current versions 4.6 and minor works!

**Comment by agonzalezm** [comment]
Elastic is providing 5.0-beta1 docker images for elasticsearch and kibana maybe you can have a look at their dockerfiles. 

https://github.com/elastic/elasticsearch-docker
https://github.com/elastic/kibana-docker

But they are not providing logstash docker image :(

**Comment by gerardorochin** [comment]
Closed because the package not was signed correctly, the next versions it's ok.
https://github.com/elastic/kibana/issues/8459#issuecomment-251202624

**Pull request closed without merging**
