### PR TITLE
Kibana 4.4.0 is eye meltingly colorful

### PR DESCRIPTION
**Pull request by gerardorochin**
release note: https://www.elastic.co/blog/kibana-4-4-0

### CODE REVIEW

**Comment by tianon** [comment]
Nice!  This LGTM, but do you think we should consider switching to their new DEBs in this PR, or just as a future modification?

> ### RPMs, DEBs, oh my!
> 
> Get ready to simplify those deployment scripts, Kibana 4.4.0 is available as an RPM and Debian (and Ubuntu!) packages. Check out the [setup docs](https://www.elastic.co/guide/en/kibana/current/setup.html#setup-repositories) for repo info!

**Comment by tianon** [comment]
(Which means this `Dockerfile` can probably finally line up nicer with `elasticsearch` and `logstash`'s :smile:)

**Comment by gerardorochin** [comment]
okay, have a reason change this PR to package now, wait a moment.

**Comment by gerardorochin** [comment]
I fixed for version 4.4.0 i will apply  for old versions too?

**Comment by yosifkit** [comment]
@gerardorochin, if they work, I would say :+1:.

**Comment by gerardorochin** [comment]
Currently only published at packages 4.1 and 4.4, I think we will include the modification in future versions.

**Comment by yosifkit** [comment]
Ok, we'll keep it to just the new version.

**Comment by yosifkit** [comment]
LGTM

``` diff
diff --git a/4.3/Dockerfile b/4.4/Dockerfile
index 70adec3..fd624e3 100644
--- a/4.3/Dockerfile
+++ b/4.4/Dockerfile
@@ -15,16 +15,20 @@ RUN arch="$(dpkg --print-architecture)" \
    && rm /usr/local/bin/gosu.asc \
    && chmod +x /usr/local/bin/gosu

-ENV KIBANA_VERSION 4.3.1
-ENV KIBANA_SHA1 115ba22882df75eb5f07330b7ad8781a57569b00
+# https://www.elastic.co/guide/en/kibana/4.4/setup.html#kibana-apt
+# https://packages.elasticsearch.org/GPG-KEY-elasticsearch
+RUN apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 46095ACC8548582C1A2699A9D27D666CD88E42B4
+
+ENV KIBANA_MAJOR_VERSION 4.4
+ENV KIBANA_VERSION 4.4.0
+
+RUN echo "deb http://packages.elastic.co/kibana/${KIBANA_MAJOR_VERSION}/debian stable main" | tee -a /etc/apt/sources.list

 RUN set -x \
-   && curl -fSL "https://download.elastic.co/kibana/kibana/kibana-${KIBANA_VERSION}-linux-x64.tar.gz" -o kibana.tar.gz \
-   && echo "${KIBANA_SHA1}  kibana.tar.gz" | sha1sum -c - \
-   && mkdir -p /opt/kibana \
-   && tar -xz --strip-components=1 -C /opt/kibana -f kibana.tar.gz \
-   && chown -R kibana:kibana /opt/kibana \
-   && rm kibana.tar.gz
+    && apt-get update \
+    && apt-get install -y --no-install-recommends kibana=${KIBANA_VERSION} \
+    && chown -R kibana:kibana /opt/kibana \
+    && rm -rf /var/lib/apt/lists/*

 ENV PATH /opt/kibana/bin:$PATH

```

**Pull request merged**
