### PR TITLE
allow basepath to be changed for reverse proxies

### PR DESCRIPTION
**Pull request by sfossen**
For 4.3 and above. see https://discuss.elastic.co/t/4-3-0-how-to-configure-your-nginx-balancer-and-apache-reverse-proxy/37351/2?u=yodog

### CODE REVIEW

**Comment by sfossen** [comment]
addresses the base of issue #28

**Comment by sfossen** [comment]
similar functionality to pull #29

**Comment by dijam** [comment]
@sfossen Do u have any plan to merge this?

**Comment by sfossen** [comment]
@dijam I don't have write access, so I can't merge it.

**Comment by yosifkit** [comment]
I am usually -1 on adding more environment variables since that can lead to a slippery slope of adding more and more variables to be able to customize/generate a config file.

We kept `ELASTICSEARCH_URL` for backwards compatibility.  We now only do the `sed` when `ELASTICSEARCH_URL` is set, so it would be fairly easy to use your own config file by mounting it (`-v /local/kibana/config/:/opt/kibana/config/:ro`) with any configuration that your situation requires.

Duplicate of #29.

**Pull request closed without merging**
